In [13]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
import pandas as pd
from pathlib import Path
from concurrent import futures

from polaris.analyze.kpi_comparator import KpiComparator
from polaris.analyze.result_kpis import ResultKPIs
from polaris.runs.convergence.convergence_iteration import ConvergenceIteration
from pathlib import Path
from polaris.runs.wtf_runner import run_baseline_analysis
from polaris.runs.calibrate import activity_generation, destination_choice, mode_choice, timing_choice
from polaris.runs.polaris_inputs import PolarisInputs
from polaris.runs.calibrate.utils import calculate_rmse
from polaris.utils.dict_utils import denest_dict

%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [6, 3]

In [15]:
def add_cols(df):
    df['sim'] = df.run_id.astype('int')
    return df

def add_runs_matching(t, project_dir, pattern='*'):
    dirs = [d.parent for d in project_dir.glob(f'{pattern}/finished')]
    for d in dirs:
        run = d.parent.name[3:] # Grab the number after Sim
        kpi = ResultKPIs.from_dir(d, db_name='Austin', population_scale_factor=0.25)
        t.add_run(kpi, f"{run:>02}")

In [16]:
project_dir=Path("/home/vsokolov/projects/timing-austin/experiments")
# t = KpiComparator()
# add_runs_matching(t,project_dir,'Sim*/Austin/')

In [17]:
# ResultKPIs.available_metrics()

In [18]:
# d = t._get_results('activity_start_distribution').reset_index()

In [19]:
# d

In [20]:
# Does not run, seems like it assumes that convergence functions from polaris studio were used manage the runs. Get a lot of sql errors. 
# t.plot_everything()

In [21]:
# d = t._get_results('skim_stats').reset_index()
# d["run_id"] = pd.to_numeric(d["run_id"])
# d =(d.sort_values('run_id')).sort_values('interval')
# df_vmt_SOV = df_vmt[df_vmt['mode'] == 'SOV'].sort_values('sim')       
# dp = d[(d.metric=='distance') & (d.run_id<10)].pivot(index='interval', columns='run_id', values='avg')
# dp.plot()

In [22]:
# d = t._get_results('vmt_vht').reset_index()
# d = d[d['mode']=='SOV']
# d["run_id"] = pd.to_numeric(d["run_id"])
# d = d.sort_values('run_id')
d

,EAT_OUT-NIGHT,EAT_OUT-AMPEAK,EAT_OUT-AMOFFPEAK,EAT_OUT-PMOFFPEAK,EAT_OUT-PMPEAK,EAT_OUT-EVENING,ERRANDS-NIGHT,ERRANDS-AMPEAK,ERRANDS-AMOFFPEAK,ERRANDS-PMOFFPEAK,...,TOTAL-PMOFFPEAK,TOTAL-PMPEAK,TOTAL-EVENING,sim,hour-AMOFFPEAK,hour-AMPEAK,hour-EVENING,hour-NIGHT,hour-PMOFFPEAK,hour-PMPEAK
0,0.015989,0.075283,0.149234,0.264490,0.292472,0.202532,0.007156,0.134764,0.291592,0.3387,...,0.206271,0.270627,0.095710,-1,NaN,NaN,NaN,NaN,NaN,NaN
1,0.006738,0.019239,0.066234,0.193198,0.109161,0.605430,0.000000,0.000000,0.000000,0.0000,...,0.215570,0.164794,0.343103,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
2,0.004903,0.014549,0.058205,0.353353,0.103807,0.465182,0.000000,0.000000,0.000000,0.0000,...,0.287853,0.171529,0.285640,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
3,0.014974,0.038952,0.109885,0.536746,0.089782,0.209661,0.000000,0.000000,0.000000,0.0000,...,0.344980,0.163279,0.171219,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
4,0.006263,0.020884,0.094696,0.147766,0.060193,0.670198,0.000000,0.000000,0.000000,0.0000,...,0.198636,0.132457,0.362126,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,0.007000,0.021925,0.056470,0.127340,0.066506,0.720759,0.000000,0.000000,0.000000,0.0000,...,0.191259,0.138036,0.395873,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
93,0.007221,0.022519,0.038686,0.128752,0.071359,0.731463,0.000000,0.000000,0.000000,0.0000,...,0.190969,0.141497,0.403335,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
94,0.007305,0.022719,0.038412,0.129587,0.067156,0.734820,0.000000,0.000000,0.000000,0.0000,...,0.191410,0.139643,0.404948,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
95,0.006883,0.022281,0.096412,0.118733,0.060193,0.695499,0.000000,0.000000,0.000000,0.0000,...,0.184289,0.130209,0.373960,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0
96,0.006886,0.022343,0.096420,0.118773,0.060223,0.695355,0.000000,0.000000,0.000000,0.0000,...,0.184252,0.130051,0.374252,/home/vsokolov/projects/timing-austin/experime...,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
# d.plot(x='run_id',y='million_VMT',marker='o',markersize=3,linewidth=0.5)
# d.plot(x='run_id',y='count',marker='o',markersize=3,linewidth=0.5)
# d.plot(x='run_id',y='speed_mph',marker='o',markersize=3,linewidth=0.5)

In [24]:
# d.to_csv('vmt_vht.csv')

In [25]:
target = timing_choice.load_target("/home/vsokolov/models/Austin/calibration_targets/timing_choice_targets.csv");
dc = denest_dict(target)
dc['sim'] = -1
d = pd.DataFrame([dc])
d

2024-07-26T08:53:29-0400 Loading timing choice target values from /home/vsokolov/models/Austin/calibration_targets/timing_choice_targets.csv
2024-07-26T08:53:29-0400 Loading timing choice target values from /home/vsokolov/models/Austin/calibration_targets/timing_choice_targets.csv: Done in 0:00:00.004817 seconds

,EAT_OUT-NIGHT,EAT_OUT-AMPEAK,EAT_OUT-AMOFFPEAK,EAT_OUT-PMOFFPEAK,EAT_OUT-PMPEAK,EAT_OUT-EVENING,ERRANDS-NIGHT,ERRANDS-AMPEAK,ERRANDS-AMOFFPEAK,ERRANDS-PMOFFPEAK,...,HOME-PMOFFPEAK,HOME-PMPEAK,HOME-EVENING,TOTAL-NIGHT,TOTAL-AMPEAK,TOTAL-AMOFFPEAK,TOTAL-PMOFFPEAK,TOTAL-PMPEAK,TOTAL-EVENING,sim
0,0.015989,0.075283,0.149234,0.26449,0.292472,0.202532,0.007156,0.134764,0.291592,0.3387,...,0.326277,0.27494,0.041016,0.011551,0.292079,0.123762,0.206271,0.270627,0.09571,-1

In [32]:
dirs = [d.parent for d in project_dir.glob('Sim*/Austin/finished')]

def get_timing_choice(dd):
    output_dbs = PolarisInputs.from_dir(dd, db_name='Austin')
    simulated = timing_choice.load_simulated(output_dbs, 0.25, False)
    dc = denest_dict(simulated)
    dc['sim'] = dd
    new_df = pd.DataFrame([dc])
    return(new_df)

t = get_timing_choice(dirs[0])
# with futures.ThreadPoolExecutor(40) as executor:
#     result = executor.map(get_timing_choice, dirs)
#     for new_df  in result:
#         d = pd.concat([d, new_df], ignore_index=True)

# d.to_csv('timing_choice_distribution.csv')

2024-07-26T08:59:46-0400 Loading timing choice simulation values
2024-07-26T09:00:11-0400 Loading timing choice simulation values: Done in 0:00:25.137122 seconds

In [37]:
t.iloc[0].values

array([0.06623354453894585, 0.019239458965527628, 0.6054304276662617,
       0.0067378272264452185, 0.193197907357386, 0.10916083424543364, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.07730589373831111, 0.03681391944261872, 0.39469518573814283,
       0.0034401057422633894, 0.23757042350588997, 0.250174471832774, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.18477389155305324, 0.04329039755151475,
       0.33523461922453723, 0.004386323835087317, 0.3129347452495131,
       0.11938002258629438, 0.07113270794896448, 0.14968687472390407,
       0.3346672556713354, 0.0043291843151521455, 0.2548917703921212,
       0.18529220694852272, 0.2607176581680831, 0.03342776203966006,
       0.37644003777148255, 0.016100094428706326, 0.09844192634560907,
       0.21487252124645892, 0.0750667330226666, 0.8206125865267159,
       0.003872777451024748, 0.03083744288105687, 0.04770393159299643,
       0.02190652852553952, 0.1552747329470083, 0.038260141031906725,
       0.3171821545765552, 0.003700342107100468, 0.39384207219157996,
       0.09174055714584933, 0.1304501511107969, 0.010515897562786094,
       0.4382743323730581, 0.002120853289973666, 0.2998533076474435,
       0.11878545801594174, 0.11313837496802796, 0.014811771909563707,
       0.5026313953758749, 0.002697277145226672, 0.2636045853711469,
       0.1031165952301599, 0.10390496424189832, 0.030156497800652323,
       0.5499506268888955, 0.009868637601364492, 0.11936323648224065,
       0.1867560369849487, 0.10588267713302024, 0.15685482040852494,
       0.34310303465178554, 0.013794903271960215, 0.21557028587236785,
       0.16479427866234123, 0.1717805815952225, 0.5621201112863498,
       0.008988853644273537, 0.0615751980294519, 0.15567241409863372,
       0.03986284134606865, 0.18722222222222223, 0.052222222222222225,
       0.15833333333333333, 0.0, 0.46111111111111114, 0.1411111111111111,
       0.2524649222601441, 0.11613576033371255, 0.024412210845657943,
       0.06171786120591581, 0.4178991277967387, 0.12737011755783087, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0,
       PosixPath('/home/vsokolov/projects/timing-austin/experiments/Sim0/Austin')],
      dtype=object)